files:
  - source: /translations/mudlet.ts
    translation: /translations/translated/mudlet_%locale_with_underscore%.%file_extension%

  - source: /translations/lua_translations/AdjustableContainer/AdjustableContainer.json
    translation: translations/lua_translations/AdjustableContainer/translated/AdjustableContainer_%locale_with_underscore%.%file_extension%
